#!/bin/bash
#
# SCRIPT: 05_extract_time_spectra.sh
#
# DESCRIPTION:
# Extracts multiple TIME-FILTERED spectra using the 'tabgtigen' method.
# It loops over user-defined time expressions, creates a GTI file for
# each, and then extracts the spectrum and responses for that interval.
#
# UPDATE: Now uses 'ftgrouppha' for grouping (supports Kaastra Optimal Binning).
#
################################################################################

# --- CONFIGURATION ---

# 1. TIME FILTER CONFIGURATION (generated by notebook)
# Format: "Expression" (Order must match OUTPUT_SUFFIXES)
TIME_FILTERS=(
    "(TIME IN [701642768.492053:701658528.492053])"
#    "(TIME IN [701596278.492053:701625198.492053])"
#    "(TIME IN [701592818.492053:701596278.492053]) || (TIME IN [701625198.492053:701628548.492053]) || (TIME IN [701632768.492053:701642768.492053]) || (TIME IN [701658528.492053:701675918.492053])"
)

# 2. OUTPUT NAMES
OUTPUT_SUFFIXES=(
    "Persistent"
#    "Dipping"
#    "Shallow"
)

# 3. GROUPING SETTINGS
# Options: "opt" (Kaastra optimal binning) OR "min" (Minimum counts)
GROUP_TYPE="optmin"
MIN_COUNTS=20

# --- STANDARD CONFIGURATION ---
IS_PILED_UP="yes"
SRC_RAWX_FILTER_STD="RAWX in [27:47]"
BKG_RAWX_FILTER="RAWX in [3:5]"
SRC_EXCISION_FILTER="!(RAWX in [36:38])"
# --- END CONFIGURATION ---


# --- 1. CHECK FOR ENVIRONMENT VARIABLES & SET PATHS ---
if [ -z "${PROJECT_ROOT}" ]; then
    echo "ERROR: Environment variable PROJECT_ROOT is not set."
    exit 1
fi
if [ -z "${OBSID}" ]; then
    echo "ERROR: Environment variable OBSID is not set."
    exit 1
fi

export OBS_DIR_ODF="${PROJECT_ROOT}/data/${OBSID}"
export PN_DIR="${PROJECT_ROOT}/products/${OBSID}/pn"
export SPEC_DIR="${PROJECT_ROOT}/products/${OBSID}/pn/spec"
export PROC_DIR="${PROJECT_ROOT}"

if [ ! -d "${OBS_DIR_ODF}" ]; then
    echo "ERROR: ODF directory not found: ${OBS_DIR_ODF}"
    exit 1
fi

# --- Re-establish SAS Setup Variables ---
ODF_DIR_CLEAN=$(echo "${OBS_DIR_ODF}" | sed 's:/*$::')
CCF_FILE="${ODF_DIR_CLEAN}/ccf.cif"
SUMMARY_FILE_NAME=$(find "${ODF_DIR_CLEAN}" -maxdepth 1 -name "*SUM.SAS" -printf "%f\n" | head -n 1)

if [ -z "${SUMMARY_FILE_NAME}" ]; then
    echo "ERROR: Cannot find *SUM.SAS file in ${ODF_DIR_CLEAN}"
    exit 1
fi

export SAS_CCF="${CCF_FILE}"
export SAS_ODF="${ODF_DIR_CLEAN}/${SUMMARY_FILE_NAME}"

# Set strict error checking
set -e

echo "--- Starting Multi-Interval Spectral Extraction ---"
echo "Grouping Method: ${GROUP_TYPE}"

mkdir -p "${SPEC_DIR}"
CLEAN_EVT_FILE="${PN_DIR}/pn_clean.evt"

if [ ! -f "${CLEAN_EVT_FILE}" ]; then
    echo "ERROR: Could not find clean event file: ${CLEAN_EVT_FILE}"
    exit 1
fi

# --- MAIN LOOP ---
for (( i=0; i<${#TIME_FILTERS[@]}; i++ )); do

    TIME_FILTER_EXPR="${TIME_FILTERS[$i]}"
    OUTPUT_SUFFIX="${OUTPUT_SUFFIXES[$i]}"

    echo ""
    echo "=========================================================="
    echo "Processing Interval $((i+1))/${#TIME_FILTERS[@]}: ${OUTPUT_SUFFIX}"
    echo "=========================================================="

    # --- 2. Define filenames ---
    SRC_SPEC="${SPEC_DIR}/pn_source_${OUTPUT_SUFFIX}.fits"
    RMF_FILE="${SPEC_DIR}/pn_rmf_${OUTPUT_SUFFIX}.rmf"
    ARF_FILE="${SPEC_DIR}/pn_arf_${OUTPUT_SUFFIX}.arf"
    GRP_SPEC_FILE="${SPEC_DIR}/pn_source_${OUTPUT_SUFFIX}_grp.pha"
    BKG_SPEC="${SPEC_DIR}/pn_bkg_${OUTPUT_SUFFIX}.fits"
    
    TEMP_GTI_FILE="${SPEC_DIR}/temp_${OUTPUT_SUFFIX}_gti.fits"
    
    # Temp files for pile-up correction
    SRC_SPEC_FULL_TEMP="${PN_DIR}/pn_source_spectrum_full_temp.fits"
    SRC_SPEC_INNER_TEMP="${PN_DIR}/pn_source_spectrum_inner_temp.fits"
    ARF_FILE_FULL_TEMP="${PN_DIR}/pn_arf_full_temp.arf"
    ARF_FILE_INNER_TEMP="${PN_DIR}/pn_arf_inner_temp.arf"

    # --- 3. Create Temporary GTI File ---
    echo "Creating temporary GTI..."
    tabgtigen table="${CLEAN_EVT_FILE}" \
        expression="${TIME_FILTER_EXPR}" \
        gtiset="${TEMP_GTI_FILE}"
    
    BASE_FILTER_EXPR="(FLAG==0)&&(PI in [500:15000])&&(PATTERN<=4)"
    GTI_FILTER_EXPR="gti(${TEMP_GTI_FILE}, TIME)"
    
    # --- 4. Determine Filters ---
    if [ "${IS_PILED_UP}" == "yes" ]; then
        FINAL_SRC_FILTER_EXPR="${BASE_FILTER_EXPR} && ${SRC_RAWX_FILTER_STD} && ${SRC_EXCISION_FILTER} && ${GTI_FILTER_EXPR}"
    else
        FINAL_SRC_FILTER_EXPR="${BASE_FILTER_EXPR} && ${SRC_RAWX_FILTER_STD} && ${GTI_FILTER_EXPR}"
    fi
    FINAL_BKG_FILTER_EXPR="${BASE_FILTER_EXPR} && ${BKG_RAWX_FILTER} && ${GTI_FILTER_EXPR}"

    # --- 5. Extract Source Spectrum ---
    echo "Extracting source spectrum..."
    evselect table="${CLEAN_EVT_FILE}" \
        withspectrumset=yes spectrumset="${SRC_SPEC}" \
        energycolumn=PI spectralbinsize=5 \
        withspecranges=yes specchannelmin=0 specchannelmax=20479 \
        expression="${FINAL_SRC_FILTER_EXPR}" \
        writedss=yes

    # --- 6. Extract Background Spectrum ---
    echo "Extracting background spectrum..."
    evselect table="${CLEAN_EVT_FILE}" \
        withspectrumset=yes spectrumset="${BKG_SPEC}" \
        energycolumn=PI spectralbinsize=5 \
        withspecranges=yes specchannelmin=0 specchannelmax=20479 \
        expression="${FINAL_BKG_FILTER_EXPR}" \
        writedss=yes

    # --- 7. Calculate BACKSCAL ---
    echo "Calculating BACKSCAL..."
    backscale spectrumset="${SRC_SPEC}" badpixlocation="${CLEAN_EVT_FILE}"
    backscale spectrumset="${BKG_SPEC}" badpixlocation="${CLEAN_EVT_FILE}"

    # --- 8. Generate RMF ---
    echo "Generating RMF..."
    rmfgen spectrumset="${SRC_SPEC}" rmfset="${RMF_FILE}"

    # --- 9. Generate ARF ---
    if [ "${IS_PILED_UP}" == "yes" ]; then
        echo "  Generating ARF (Pile-up correction)..."
        INNER_CORE_RAWX=$(echo "${SRC_EXCISION_FILTER}" | sed -e 's/!//' -e 's/(//' -e 's/)//')
        INNER_CORE_FILTER_EXPR="${BASE_FILTER_EXPR} && ${INNER_CORE_RAWX} && ${GTI_FILTER_EXPR}"
        FULL_SRC_FILTER_EXPR_TEMP="${BASE_FILTER_EXPR} && ${SRC_RAWX_FILTER_STD} && ${GTI_FILTER_EXPR}"

        # Extract temp spectra for ARF generation
        evselect table="${CLEAN_EVT_FILE}" withspectrumset=yes spectrumset="${SRC_SPEC_FULL_TEMP}" \
            expression="${FULL_SRC_FILTER_EXPR_TEMP}" energycolumn=PI spectralbinsize=5 \
            withspecranges=yes specchannelmin=0 specchannelmax=20479 writedss=yes
            
        evselect table="${CLEAN_EVT_FILE}" withspectrumset=yes spectrumset="${SRC_SPEC_INNER_TEMP}" \
            expression="${INNER_CORE_FILTER_EXPR}" energycolumn=PI spectralbinsize=5 \
            withspecranges=yes specchannelmin=0 specchannelmax=20479 writedss=yes

        # Generate temp ARFs
        arfgen spectrumset="${SRC_SPEC_FULL_TEMP}" arfset="${ARF_FILE_FULL_TEMP}" \
            withrmfset=yes rmfset="${RMF_FILE}" badpixlocation="${CLEAN_EVT_FILE}" detmaptype=psf

        arfgen spectrumset="${SRC_SPEC_INNER_TEMP}" arfset="${ARF_FILE_INNER_TEMP}" \
            withrmfset=yes rmfset="${RMF_FILE}" badpixlocation="${CLEAN_EVT_FILE}" detmaptype=psf

        # Subtract
        addarf "${ARF_FILE_FULL_TEMP} ${ARF_FILE_INNER_TEMP}" "1.0 -1.0" "${ARF_FILE}" clobber=yes
    else
        echo "  Generating ARF (Standard)..."
        arfgen spectrumset="${SRC_SPEC}" arfset="${ARF_FILE}" \
            withrmfset=yes rmfset="${RMF_FILE}" badpixlocation="${CLEAN_EVT_FILE}" detmaptype=psf
    fi

    # --- 10. Group the Source Spectrum (FIXED) ---
    echo "Grouping spectrum: $(basename ${GRP_SPEC_FILE})"

    # Sanitize/Check files before grouping
    RMF_ARG=""
    BKG_ARG=""
    [ -f "${RMF_FILE}" ] && RMF_ARG="respfile=${RMF_FILE}"
    [ -f "${BKG_SPEC}" ] && BKG_ARG="backfile=${BKG_SPEC}"

    if [ "$GROUP_TYPE" == "opt" ]; then
        ftgrouppha infile="${SRC_SPEC}" \
                   outfile="${GRP_SPEC_FILE}" \
                   grouptype="opt" \
                   ${RMF_ARG} \
                   ${BKG_ARG} \
                   clobber=yes
    else
        ftgrouppha infile="${SRC_SPEC}" \
                   outfile="${GRP_SPEC_FILE}" \
                   grouptype="optmin" \
                   groupscale="${MIN_COUNTS}" \
                   ${RMF_ARG} \
                   ${BKG_ARG} \
                   clobber=yes
    fi

    # IMPORTANT: Remove the internal paths to prevent PyXSPEC from getting confused
    # by the hardcoded absolute paths in the header.
    fparkey "none" "${GRP_SPEC_FILE}[1]" RESPFILE
    fparkey "none" "${GRP_SPEC_FILE}[1]" BACKFILE
    fparkey "none" "${GRP_SPEC_FILE}[1]" ANCRFILE


    # --- 11. Clean up temporary files ---
    rm -f "${TEMP_GTI_FILE}"
    if [ "${IS_PILED_UP}" == "yes" ]; then
        rm -f "${SRC_SPEC_FULL_TEMP}" "${SRC_SPEC_INNER_TEMP}" \
              "${ARF_FILE_FULL_TEMP}" "${ARF_FILE_INNER_TEMP}"
    fi

    echo "Finished interval: ${OUTPUT_SUFFIX}"

done
echo ""
echo "Multi-Interval extraction and grouping complete."