#!/bin/bash
#
# SCRIPT: 05_extract_time_spectra.sh
#
# DESCRIPTION:
# Extracts multiple TIME-FILTERED spectra using the 'tabgtigen' method.
# It loops over user-defined time expressions, creates a GTI file for
# each, and then extracts the spectrum and responses for that interval.
#
# UPDATE: Now uses 'ftgrouppha' for grouping (supports Kaastra Optimal Binning).
#
################################################################################

# --- Source shared setup (env checks, SAS, paths, instrument config) ---
source "$(dirname "$0")/sas_common.sh"

# --- CONFIGURATION ---

# 1. TIME FILTER CONFIGURATION (generated by notebook)
# Format: "Expression" (Order must match OUTPUT_SUFFIXES)
TIME_FILTERS=(
    "(TIME IN [701642768.492053:701658528.492053])"
    "(TIME IN [701596278.492053:701625198.492053])"
    "(TIME IN [701592818.492053:701596278.492053]) || (TIME IN [701625198.492053:701628548.492053]) || (TIME IN [701632768.492053:701642768.492053]) || (TIME IN [701658528.492053:701675918.492053])"
)

# 2. OUTPUT NAMES
OUTPUT_SUFFIXES=(
    "Persistent"
    "Dipping"
    "Shallow"
)

# 3. GROUPING SETTINGS
# Options: "opt" (Kaastra optimal binning) OR "min" (Minimum counts)
GROUP_TYPE="optmin"
MIN_COUNTS=20

# --- END CONFIGURATION ---

# Set strict error checking
set -e

echo "--- Starting Multi-Interval Spectral Extraction ---"
echo "Grouping Method: ${GROUP_TYPE}"

mkdir -p "${SPEC_DIR}"

if [ ! -f "${CLEAN_EVT_FILE}" ]; then
    echo "ERROR: Could not find clean event file: ${CLEAN_EVT_FILE}"
    exit 1
fi

# --- MAIN LOOP ---
for (( i=0; i<${#TIME_FILTERS[@]}; i++ )); do

    TIME_FILTER_EXPR="${TIME_FILTERS[$i]}"
    OUTPUT_SUFFIX="${OUTPUT_SUFFIXES[$i]}"

    echo ""
    echo "=========================================================="
    echo "Processing Interval $((i+1))/${#TIME_FILTERS[@]}: ${OUTPUT_SUFFIX}"
    echo "=========================================================="

    # --- 2. Define filenames ---
    SRC_SPEC="${SPEC_DIR}/pn_source_${OUTPUT_SUFFIX}.fits"
    RMF_FILE="${SPEC_DIR}/pn_rmf_${OUTPUT_SUFFIX}.rmf"
    ARF_FILE="${SPEC_DIR}/pn_arf_${OUTPUT_SUFFIX}.arf"
    GRP_SPEC_FILE="${SPEC_DIR}/pn_source_${OUTPUT_SUFFIX}_grp.pha"
    BKG_SPEC="${SPEC_DIR}/pn_bkg_${OUTPUT_SUFFIX}.fits"
    TEMP_GTI_FILE="${SPEC_DIR}/temp_${OUTPUT_SUFFIX}_gti.fits"

    # --- 3. Create Temporary GTI File ---
    echo "Creating temporary GTI..."
    tabgtigen table="${CLEAN_EVT_FILE}" \
        expression="${TIME_FILTER_EXPR}" \
        gtiset="${TEMP_GTI_FILE}"
    
    BASE_FILTER_EXPR="(FLAG==0)&&(PI in [500:15000])&&(PATTERN<=4)"
    GTI_FILTER_EXPR="gti(${TEMP_GTI_FILE}, TIME)"
    
    # --- 4. Determine Filters ---
    FINAL_SRC_FILTER_EXPR=$(build_src_filter "${BASE_FILTER_EXPR}" "${GTI_FILTER_EXPR}")
    FINAL_BKG_FILTER_EXPR="${BASE_FILTER_EXPR} && ${BKG_RAWX_FILTER} && ${GTI_FILTER_EXPR}"

    # --- 5. Extract Source Spectrum ---
    echo "Extracting source spectrum..."
    extract_spectrum "${SRC_SPEC}" "${FINAL_SRC_FILTER_EXPR}"

    # --- 6. Extract Background Spectrum ---
    echo "Extracting background spectrum..."
    extract_spectrum "${BKG_SPEC}" "${FINAL_BKG_FILTER_EXPR}"

    # --- 7. Calculate BACKSCAL ---
    echo "Calculating BACKSCAL..."
    backscale spectrumset="${SRC_SPEC}" badpixlocation="${CLEAN_EVT_FILE}"
    backscale spectrumset="${BKG_SPEC}" badpixlocation="${CLEAN_EVT_FILE}"

    # --- 8. Generate RMF ---
    echo "Generating RMF..."
    rmfgen spectrumset="${SRC_SPEC}" rmfset="${RMF_FILE}"

    # --- 9. Generate ARF ---
    generate_arf "${SRC_SPEC}" "${ARF_FILE}" "${RMF_FILE}" "${BASE_FILTER_EXPR}" "${GTI_FILTER_EXPR}"

    # --- 10. Group the Source Spectrum ---
    echo "Grouping spectrum: $(basename ${GRP_SPEC_FILE})"

    # Sanitize/Check files before grouping
    RMF_ARG=""
    BKG_ARG=""
    [ -f "${RMF_FILE}" ] && RMF_ARG="respfile=${RMF_FILE}"
    [ -f "${BKG_SPEC}" ] && BKG_ARG="backfile=${BKG_SPEC}"

    if [ "$GROUP_TYPE" == "opt" ]; then
        ftgrouppha infile="${SRC_SPEC}" \
                   outfile="${GRP_SPEC_FILE}" \
                   grouptype="opt" \
                   ${RMF_ARG} \
                   ${BKG_ARG} \
                   clobber=yes
    else
        ftgrouppha infile="${SRC_SPEC}" \
                   outfile="${GRP_SPEC_FILE}" \
                   grouptype="optmin" \
                   groupscale="${MIN_COUNTS}" \
                   ${RMF_ARG} \
                   ${BKG_ARG} \
                   clobber=yes
    fi

    # IMPORTANT: Remove the internal paths to prevent PyXSPEC from getting confused
    # by the hardcoded absolute paths in the header.
    fparkey "none" "${GRP_SPEC_FILE}[1]" RESPFILE
    fparkey "none" "${GRP_SPEC_FILE}[1]" BACKFILE
    fparkey "none" "${GRP_SPEC_FILE}[1]" ANCRFILE

    # --- 11. Clean up temporary files ---
    rm -f "${TEMP_GTI_FILE}"

    echo "Finished interval: ${OUTPUT_SUFFIX}"

done
echo ""
echo "Multi-Interval extraction and grouping complete."